name: crystfelparser
channels:
  - defaults
  - conda-forge
dependencies:
  - joblib=1.0.1
  - matplotlib=3.3.2
  - numpy=1.19.2
  - pandas=1.1.3
  - pip=20.2.4
  - python=3.7.4
  - scikit-learn=0.23.2
  - scipy=1.5.2
  - h5py=3.2.1  
  - hdf5=1.10.6
  - bitshuffle=0.4.1
  - ipython
